# permissions for end users to view litetests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: litetest-viewer-role
rules:
- apiGroups:
  - test.ability.app
  resources:
  - litetests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.ability.app
  resources:
  - litetests/status
  verbs:
  - get
